#!/bin/sh
set -e
errors=$(/usr/local/php/sbin/php-fpm --fpm-config /usr/local/php/etc/php-fpm.conf -c /usr/local/php/etc/php.ini -t 2>&1 | grep "\[ERROR\]" || true);
if [ -n "$errors" ]; then
    echo "Please fix your configuration file..."
    echo $errors
    exit 1
fi
exit 0
