
- name: Monitoring | Install application
  apt: name={{item}} update_cache=yes cache_valid_time=3600
  with_items:
    - ntop
    - htop
    - iotop
    - snmpd
    - mtr
    - nmon

# - name: Monitoring | Config application

# https://www.unixmen.com/how-to-monitor-linux-clients-using-shinken/
