
# download file e metterli in locale
# * https://gist.github.com/dorneanu/9f940b2ded9c05b5be9f#file-chroot-sh
# * https://gist.github.com/dorneanu/9f940b2ded9c05b5be9f#file-n2chroot
# * https://gist.github.com/dorneanu/9f940b2ded9c05b5be9f#file-nginx-chroot (nginx-chroot  to copy to /etc/init.d/*)
# * https://gist.github.com/dorneanu/9f940b2ded9c05b5be9f#file-php5-fpm-chroot (php5-fpm-chroot to copy to /etc/init.d/*)
- name: check uncompress application presence
  apt: name={{item}} update_cache=yes cache_valid_time=3600
  with_items:
    - unzip
    - tar

- include: jail.yml

- name: n2chroot script
  template: src=n2chroot.j2 dest=/root/scripts/n2chroot mode=0755

- include: nginx.yml
#- include: nginx-systemd.yml
- include: nginx-systemv.yml

- include: php.yml
#- include: php-systemd.yml
- include: php-systemv.yml

- name: n2chroot script
  file: path=/root/scripts/n2chroot state=absent
