##
## http://docs.ansible.com/ansible/ufw_module.html
##

- name: install ufw
  apt: name={{item}}
  with_items:
    - iptables
    - ufw
- name: disable ipv6
  copy: src=ufw.yml dest=/etc/default/ufw #ci vorrebbe un sed!
- name: ufw reset
  ufw: state=reset
- name: ssh enable
  ufw: rule=allow name=OpenSSH #per non chiudersi fuori
- name: ufw start
  ufw: state=enabled policy=allow
- name: ufw enable service
  ufw: rule=allow port={{ item.port }}  proto={{ item.proto }}
  with_items: "{{service_list}}"
- name: ufw deny all
  ufw: policy=deny #means the packet is discarded