%% Diagramma di sequenza
sequenceDiagram
    participant App
    participant Server
    App->>Server: 1. HTTP POST /workspace/{id}/part
    alt success
        Server->>App: 2a. HTTP 201 {"id":""}
    else failure
        Server->>App: 2b. HTTP 4XX
    end
