%% Diagramma di sequenza
sequenceDiagram
    participant App
    participant Server
    participant Hybridauth (External)
    participant Facebook (External)
    Note over Server,Hybridauth (External): php shared session
    App->>+Server: 1. HTTP GET /user/signup?authMode=Facebook
    Server-->>App: HTTP 302 redirect Hybridauth (External)
    App->>+Hybridauth (External): 2. HTTP GET ?hauth.start=Facebook
    Hybridauth (External)-->>App: HTTP 302 redirect Facebook
    App->>+Facebook (External): 3. inserisci dati login
    Facebook (External)-->>-App: HTTP 302 redirect Hybridauth (External)
    App->>Hybridauth (External): 4. HTTP GET ?hauth.done=Facebook
    Hybridauth (External)-->>-App: HTTP 302 redirect Server
    App->>Server: 5. HTTP GET /security/callback?authMode=facebook
    Server-->>-App: Token/Sessione
    Note over Server,Facebook (External): https://developers.facebook.com/docs/facebook-login/access-tokens/expiration-and-extension
