- name: config dir
  file: path=/etc/collectd state=directory

- name: config before install prevent crash
  template: src=collectd.conf.j2 dest=/etc/collectd/collectd.conf

- name: install package collectd
  apt: package="{{ item }}" state=present
  with_items:
    - collectd
    - collectd-core
