- name: config dir
  file: path=/etc/collectd state=directory

- name: config before install prevent crash
  template: src=collectd.conf.j2 dest=/etc/collectd/collectd.conf

- name: install package collectd
  apt: package="{{ item }}" state=present
  with_items:
    - collectd=5.6.1-2~bpo8+1
    - collectd-core=5.6.1-2~bpo8+1
    - libhiredis-dev
    - libhiredis0.10
