---
# @see: https://github.com/RaymiiOrg/ansible/tree/master/goaccess

- file: path=/var/keys state=directory owner=root

# - get_url: url=http://deb.goaccess.io/gnugpg.key dest=/var/keys/goaccess_signing.key
#   register: result

# - command: "apt-key add /var/keys/goaccess_signing.key"
#   when: result.changed

- apt_key: url=http://deb.goaccess.io/gnugpg.key state=present

- apt_repository: repo='deb http://deb.goaccess.io jessie main' state=present

- apt: update_cache=yes

- action: apt name=goaccess state=latest

- action: apt name=xz-utils state=latest

# libtokyocabinet-dev serve per usare lo storage...

- template: src=goaccess.conf.j2 dest=/etc/goaccess.conf backup=yes
  tags:
    - config

# - cron: name="goaccess" minute=5 hour=0
#         user="root" job="zcat -f /var/log/nginx/access.log* | goaccess --no-progress -a > /var/www/report.html"
#         cron_file=ansible_goaccess

# - cron: name="goaccess-latest" minute=0
#         user="root" job="goaccess --no-progress -f /var/log/nginx/access.log -a > /var/www/report-lastlog.html"
#         cron_file=ansible_goaccess-latest
