---
# file: group_vars/all
locale_lang: en_US.UTF-8
installed_locale:
  - en_US.UTF-8
  - it_IT.UTF-8

base_sysctl:
  - { name: kernel.core_uses_pid, value: 1 }
  - { name: kernel.kptr_restrict, value: 1 }
  - { name: kernel.sysrq, value: 0 }
  - { name: net.ipv4.conf.all.log_martians, value: 1 }
  - { name: net.ipv4.conf.all.accept_redirects, value: 0}
  - { name: net.ipv4.conf.all.forwarding, value: 0 }
  - { name: net.ipv4.conf.default.log_martians, value: 1 }

base_application:
  - supervisor
  - less
  - vim
  - net-tools
  - nano
  - curl
  - rsync
  - screen
  - ack-grep
  - vnstat
  - ntpdate
  - unzip
  - cron
  - wget
  - iptraf
  - dstat
  - sudo
  - python-pip
  - apt-rdepends
  - zip

base_unwanted_application:
  - bind9-host
  - libbind9-90
  - libnfsidmap2:amd64
  - nfs-common
  - rpcbind

sudoers_sudoers:
  defaults:
    - env_reset
    - exempt_group=sudo
    - mail_badpass
    - secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  privileges:
    - name: "root"
      entry: "ALL=(ALL:ALL) ALL"
    - name: "%admin"
      entry: "ALL = (ALL) NOPASSWD:ALL"
    - name: "developer"
      entry: "ALL = (ALL) NOPASSWD:ALL"

apt_version_name: jessie
interface: "{{ansible_default_ipv4.interface}}"

hostname_avahi: no

no_root_user: developer

service_list:
 - { port: 443, proto: 'tcp' }
 - { port: 80, proto: 'tcp' }

base_scripts:
  - apt-check-security.sh

application_environment: production


#admin_email: ???
#cron_mail_to: root@localhost
#alert_mail_to: root@localhost
#fail2ban_destemail: 'root@{{ ansible_domain }}'
