---
# file: group_vars/all

base_application:
  - supervisor
  - less
  - vim
  - net-tools
  - nano
  - curl
  - rsync
  - screen
  - ack-grep
  - vnstat
  - ntpdate
  - unzip
  - cron
  - wget
  - iptraf
  - dstat
  - sudo
  - python-pip
  - apt-rdepends
  - zip

base_unwanted_application:
  - bind9-host
  - libbind9-90
  - libnfsidmap2:amd64
  - nfs-common
  - rpcbind

apt_version_name: jessie
interface: "{{ansible_default_ipv4.interface}}"

hostname_avahi: no

no_root_user: developer

service_list:
 - { port: 443, proto: 'tcp' }
 - { port: 80, proto: 'tcp' }

base_scripts:
  - apt-check-security.sh

application_environment: production


#admin_email: ???
#cron_mail_to: root@localhost
#alert_mail_to: root@localhost
#fail2ban_destemail: 'root@{{ ansible_domain }}'
