base_sysctl:
  - { name: kernel.core_uses_pid, value: 1 }
  - { name: kernel.kptr_restrict, value: 1 }
  - { name: kernel.sysrq, value: 0 }
  - { name: net.ipv4.conf.all.log_martians, value: 1 }
  - { name: net.ipv4.conf.default.log_martians, value: 1 }
  - { name: net.ipv4.conf.eth0.log_martians, value: 1 }
  - { name: net.ipv4.conf.lo.log_martians, value: 1 }
  - { name: net.ipv4.conf.all.accept_redirects, value: 0}
  - { name: net.ipv4.conf.all.forwarding, value: 0 }
  - { name: net.ipv4.conf.default.log_martians, value: 1 }
  # Do not send ICMP redirects (we are not a router)
  - { name: net.ipv4.conf.all.send_redirects, value: 0 }
  # https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Security_Guide/sect-Security_Guide-Server_Security-Disable-Source-Routing.html
  - { name: net.ipv4.conf.all.accept_source_route, value: 0 }
