---
# file: site.yml
- hosts: all

  roles:
    - { role: tersmitten.sudoers, tags: ["base"] }
    - { role: locale, tags: ["base"] }
    - { role: ANXS.openssh, tags: ["base"] }
    - { role: ansible-hostname, tags: ["base"] }
    - { role: base, tags: ["base"] }

  vars:
    apt_version_name: jessie
    interface: "{{ansible_default_ipv4.interface}}"

    hostname_avahi: no

    no_root_user: developer

    service_list:
     - { port: 443, proto: 'tcp' }
     - { port: 80, proto: 'tcp' }

    base_scripts:
      - apt-check-security.sh

- include: plays/webservers.yml
