---
# file: site.yml
- hosts: all

  vars:
    date: "{{ lookup('pipe', 'date +%Y%m%d-%H%M') }}"
    shortdate: "{{ lookup('pipe', 'date +%Y%m%d') }}"

- include: plays/init.yml

- include: plays/webservers.yml

- include: plays/end.yml

# post_tasks:
# notifica a qualcuno?
