---
# Install tasks file for ansible-linux-security-role
# Linux Malware Detect isn't available as a package
# Lynis updates often and package tends to be behind
# everything else is apt-get installed.

  - name: install packages
    apt:
      pkg: "{{ item }}"
      state: latest
    with_items:
      - zip
      - nmap
      - cron
      - wget
      - ntpdate
    tags: bootstrap

  - name: install packages
    apt:
      pkg: "{{ item }}"
    with_items:
      - chkrootkit=0.50-3.2  #anti rootkit
      - lsat=0.9.7.1-2.1     #rootkit, backdoor, sniffer and exploit scanner
      - rkhunter=1.4.2-5
      - tiger=1:3.2.3-14
    tags: scanners

  - name: rkhunter | Make sure rkhunter has latest defs
    command: rkhunter --propupd
    changed_when: False
    tags: scanners

  - name: Create root's download dir
    file: path=/root/downloads state=directory
    tags: bootstrap

  - name: check maldet installed
    stat: path=/usr/local/maldetect
    register: maldetect_installed

  - name: Maldet | download the Linux Malware Detect tar.gz file from rfxn.com
    get_url: url=http://www.rfxn.com/downloads/{{maldetect_version}}.tar.gz dest="/root/downloads/{{maldetect_version}}.tar.gz"
    tags: maldet
    tags: scanners
    when: maldetect_installed.stat.exists == False

  - name: Maldet | Unarchive copied package
    unarchive: src=/root/downloads/{{maldetect_version}}.tar.gz dest=/root/downloads copy=no
    tags: maldet
    tags: scanners
    when: maldetect_installed.stat.exists == False

  - name: Maldet | Install Linux Malware Detect
    shell: /root/downloads/{{maldetect_version}}/install.sh chdir=/root/downloads/{{maldetect_version}}
    changed_when: False
    tags: maldet
    tags: scanners
    when: maldetect_installed.stat.exists == False

    #TODO: rimuovi la directory maldetect-15

  - name: Maldet | Add maldet to crontab at a random hour
    cron: name="Run Maldet" hour="{{ 3|random}}" minute="{{ 57 |random}}" job="{{ maldet_cron }}" state=present
    changed_when: False
    tags:
       - maldet
       - cron
       - scanners
    when: maldetect_installed.stat.exists == False

  - name: check lynis installed
    stat: path=/usr/local/lynis
    register: lynis_installed

  - name: Lynis | Create Lynis's download dir
    file: path=/root/downloads/lynis state=directory
    tags: lynis
    tags: scanners
    when: lynis_installed.stat.exists == False

  - name: Lynis | Grab the latest Lynis
    get_url: url=https://cisofy.com/files/{{ lynis_version }} dest=/root/downloads
    tags: lynis
    tags: scanners
    when: lynis_installed.stat.exists == False

  - name: Lynis | Unarchive copied package
    unarchive: src=/root/downloads/{{ lynis_version }} dest=/root/downloads copy=no
    tags: lynis
    tags: scanners
    when: lynis_installed.stat.exists == False

  - name: Lynis | Install Lynis
    command: mv /root/downloads/lynis /usr/local/lynis
    tags: lynis
    tags: scanners
    when: lynis_installed.stat.exists == False

  - name: Lynis | Add Lynis to crontab at a random hour
    cron: name="Run Lynis" hour="{{ 4|random}}" minute="{{ 59 |random}}" job="{{ lynis_cron }}" state=present
    changed_when: False
    tags:
       - lynis
       - cron
       - scanners
    when: lynis_installed.stat.exists == False

   #TODO: rimuovi la directory downloads
