---
# tasks file for ansible-linux-security-role

- name: install packages
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items:
    - ntpdate
  tags: bootstrap

- name: make sure the time is correct
  shell: "ntpdate -u {{ntp_server}}"

# - name: Update APT package cache
#   action: apt update_cache=yes
#   changed_when: False

- include: install.yml

#- include: tasks.yml
