- hosts: all

  tasks:
    - name: remove compile application
      apt: name={{item}} state=absent
      with_items:
        - binutils
        - cpp-4.9
        - gcc-4.9
        - libasan1
        - libatomic1
        - libcilkrts5
        - libcloog-isl4
        - libgcc-4.9-dev
        - libgomp1
        - libisl10
        - libitm1
        - liblsan0
        - libmpc3
        - libmpfr4
        - libquadmath0
        - libtsan0
        - libubsan0
        - build-essential
        - dpkg-dev
        - g++-4.9
        - libbz2-dev
        - libc-dev-bin
        - libc6-dev
        - libdpkg-perl
        - libpcre3-dev
        - libpcrecpp0
        - libssl-dev=1.0.2j-1~bpo8+1
        - libstdc++-4.9-dev
        - zlib1g-dev
        - linux-libc-dev
        - autoconf
        - automake
        - autotools-dev
      when: application_environment != "developer"
