- hosts: all

  # tasks:
  #   - name: remove compile application
  #     apt: name={{item}} state=absent
  #     with_items:
  #     when: application_environment != "developer"

  roles:
    - { role: compiler, tags: ["clean"], compiler_mode: absent }
    # - { role: linux-security-check, tags: ["hardening"] }
