- hosts: all
  remote_user: vagrant
  sudo: true
  tasks:
    - authorized_key: user=root key="{{ lookup('file', './ssh/root.key.pub') }}"
    - user: name=developer shell=/bin/bash groups=admin append=yes createhome=yes
    - authorized_key: user=developer key="{{ lookup('file', './ssh/developer.key.pub') }}"


# deb http://httpredir.debian.org/debian jessie-backports main contrib non-free
