---
# caratteristiche di un webservers
- name: webservers.yml | All roles
  hosts: webservers

  roles:
    - { role: geerlingguy.mysql, tags: ["database"] }
    - { role: geerlingguy.redis, tags: ["database"] }
    # - { role: php-jail,          tags: ["internalserver"] }
    - { role: php,               tags: ["internalserver"] }
    - { role: nginx,             tags: ["internalserver"] }
    - { role: haproxy,           tags: ["frontend"] }

    - { role: logrotate,         tags: ["logging"] }

    - { role: goaccess,          tags: ["monitoring"] }
    # - { role: stats,             tags: ["monitoring"] }

    #- { role: geerlingguy.composer, tags: ["application"] }
