# listen ft_web
#  option http-server-close
#  mode http
#  bind 127.0.0.1:8090 name http
#  default_backend bk_web
#
# backend bk_web
#  option http-server-close
#  mode http
#  compression algo gzip
#  compression type text/html text/plain text/css
#  server localhost 127.0.0.1:80

# Test
#curl -o/dev/null -D - "http://127.0.0.1:8090/style.css"
#curl -o/dev/null -D - "http://127.0.0.1:8090/style.css" -H "Accept-Encoding: gzip"


haproxy_ssl_cert: /etc/ssl/localcerts/selfsigned.combo.pem

#DEBUG
#haproxy_dontlog_normal: false

haproxy:
   default_backend: www-workspace
   redirects:
     - { acl: "no-www", dest: "http://{{ inventory_hostname }}", code: 301}
   domains:
     - { domain: "{{ inventory_hostname | regex_replace('^(.*).','') }}",  acl: "no-www" }
     - { domain: "{{ inventory_hostname }}",  path_beg: "workspace",  backend: { name: "www-workspace" , reqirep: '^([^\ :]*)\ /workspace/(.*) \1\ /\2', array: [ { ip: "127.0.0.1", port: 9081} ] } }
     - { domain: "{{ inventory_hostname }}", path_beg: "auth", backend: { name: "www-auth" , reqirep: '^([^\ :]*)\ /auth/(.*) \1\ /\2', array: [ { ip: "127.0.0.1", port: 9082} ] } }
     - { domain: "{{ inventory_hostname }}", path_beg: "stream", backend: { name: "www-upload" , array: [ { ip: "127.0.0.1", port: 9090} ] } }

haproxy_version: 1.7.5-1~bpo8+1
liblua5_version: 5.3.1-1~bpo8+1
libssl1_version: 1.0.2k-1~bpo8+1
