# in questa dir vengo messi i config di connect a mysql (in caso si usi sudo probabilmente da cambiare)
mysql_user_home: /root

mysql_slow_query_log_enabled: yes
mysql_slow_query_log_file: /var/log/mysql-slow.log
mysql_slow_query_time: 2
mysql_bind_address: '127.0.0.1'
mysql_root_password: r00t
mysql_databases:
  - name: workspace
    encoding: utf8
    collation: utf8_general_ci
mysql_users:
  - name: workspace_user
    host: "%"
    password: workspace
    priv: "workspace.*:ALL"
