---
# # The user to run nginx
#
# nginx_user: www-data
#
# # A list of directives for the events section.
# nginx_events_params:
#  - worker_connections 512
#  - debug_connection 127.0.0.1
#  - use epoll
#  - multi_accept on
#
#
# # A list of hashs that define additional configuration
# nginx_configs:
#     gzip:
#       - gzip on
#       - gzip_disable msie6

nginx_remove_default_vhost: true

# IMPEDISCO DI LOGGARE I 200/300 (caso auth non servono)
nginx_extra_login_options: |
  map $status $loggable {
      ~^[23]  0;
      default 1;
  }

nginx_fast_cgi_signature: false

nginx_extra_http_options: |
  proxy_buffering    off;

nginx_vhosts:
  - listen: "9081 default_server"
    server_name: "workspace.local"
    root: "/var/www/workspace.local/public"
    index: "index.php index.html index.htm"
    #error_page: ""
    directory_log: "/var/www/workspace.local/log"
    access_log: "access.log combined"
    error_log: "error.log"
    extra_parameters: |
      location /assets/ {
         alias /var/www/workspace.local/assets/;
      }
      location ~ \.php$ {
              fastcgi_split_path_info ^(.+\.php)(/.+)$;
              fastcgi_pass unix:/var/run/php5-fpm.workspace.sock;
              fastcgi_index index.php;
              fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
              include fastcgi_params;
          }

  - listen: "9082"
    server_name: "auth.local"
    root: "/var/www/auth.local/public"
    index: "index.php index.html index.htm"
    #error_page: ""
    directory_log: "/var/www/auth.local/log"
    access_log: "access.log combined if=$loggable"
    error_log: "error.log"
    extra_parameters: |
      location ~ \.php$ {
              fastcgi_split_path_info ^(.+\.php)(/.+)$;
              fastcgi_pass unix:/var/run/php5-fpm.auth.sock;
              fastcgi_index index.php;
              fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
              include fastcgi_params;
          }
