---
# The user to run nginx

nginx_user: www-data

# A list of directives for the events section.
nginx_events_params:
 - worker_connections 512
 - debug_connection 127.0.0.1
 - use epoll
 - multi_accept on

# A list of hashs that define the servers for nginx,
# as with http parameters. Any valid server parameters
# can be defined here.
nginx_sites:
 default:
      - listen 8080
      - server_name _
      - root "/usr/share/nginx/html"
      - index index.html

# A list of hashs that define additional configuration
nginx_configs:
    gzip:
      - gzip on
      - gzip_disable msie6
