---

- name: install haproxy
  apt: name="{{ item }}"
  with_items: "{{ haproxy_pakage_to_install }}"

- name: Check if iprange is installed.
  stat: "path=/usr/local/bin/iprange"
  register: iprange

- include: iprange.yml
  when: not iprange.stat.exists

- name: clean geoip directory
  file: path=/etc/haproxy/geoip state=absent

- name: create geoip directory
  file: path=/etc/haproxy/geoip state=directory

- name: abuser list
  file: path=/etc/haproxy/abuser.lst state=touch

- name: generate country continent
  shell: for c in `fgrep -v '-' {{ geoip_directory }}/country_continent.csv | grep -v "country" | sort -t',' -k 2` ; do echo $c | awk -F',' '{ print $1 >> $2".continent" }' ; done
  args:
    chdir: /etc/haproxy/geoip

- name: generate subnet country
  shell: cut -d, -f1,2,5 "{{ geoip_directory }}/GeoIPCountryWhois.csv" | /usr/local/bin/iprange |  sed 's/"//g' | awk -F' ' '{ print $1 >> $2".subnets" }'
  args:
    chdir: /etc/haproxy/geoip

- name: generate subnet county continent
  shell: for f in `ls *.continent` ; do for c in $(cat $f) ; do cat ${c}.subnets >> ${f%%.*}.continent.subnets ; done ;  done
  args:
    chdir: /etc/haproxy/geoip

- name: generate
  shell: cut -d, -f1,2,5 "{{ geoip_directory }}/GeoIPCountryWhois.csv" | /usr/local/bin/iprange | sed 's/"//g' | awk -F' ' '{ print $1" "$2 }' > geoip.lst
  args:
    chdir: /etc/haproxy/geoip

- name: setup haproxy
  template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg backup=yes
  notify: restart haproxy
  # http://docs.ansible.com/ansible/haproxy_module.html
